export const URL_ANIME_SEARCH: string = 'https://api.jikan.moe/v4/anime'
export const URL_TOP_ANIME: string = 'https://api.jikan.moe/v4/top/anime'
export const URL_MANGA_SEARCH: string = 'https://api.jikan.moe/v4/manga'
export const URL_TOP_MANGA: string = 'https://api.jikan.moe/v4/top/manga'
export const URL_RANDOM_ANIME: string = 'https://api.jikan.moe/v4/random/anime?sfw=false'
export const URL_RANDOM_MANGA: string = 'https://api.jikan.moe/v4/random/manga?sfw=false'