export enum AnimeActionTypes{
    SET_ANIMES = "SET_ANIMES",
    SET_ANIME_ERROR = "SET_ANIME_ERROR",
    SET_RANDOM_ANIME = "SET_RANDOM_ANIME",
    SET_PAGINATED_ANIMES = "SET_PAGINATED_ANIMES",
    SET_LAST_PAGE = "SET_LAST_PAGE"
}