export enum MangaActionTypes{
    SET_MANGAS = "SET_MANGAS",
    SET_MANGA_ERROR = "SET_MANGA_ERROR",
    SET_RANDOM_MANGA = "SET_RANDOM_MANGA",
    SET_PAGINATED_MANGAS = "SET_PAGINATED_MANGAS",
    SET_LAST_MANGA_PAGE = "SET_LAST_MANGA_PAGE",
    SET_IS_MANGA = "SET_IS_MANGA",
    SET_MANGA_SEARCH_RESULT = "SET_MANGA_SEARCH_RESULT",
    SET_MANGA_SEARCH_VALUE = "SET_MANGA_SEARCH_VALUE",
    SET_MANGA_GENRES = "SET_MANGA_GENRES",
    SET_MANGA_BY_GENRE = "SET_MANGA_BY_GENRE",
    SET_CURRENT_MANGA_TITLE = "SET_CURRENT_MANGA_TITLE",
    SET_CURRENT_MANGA_PAGE = "SET_CURRENT_MANGA_PAGE"
}