export enum MangaActionTypes{
    SET_MANGAS = "SET_MANGAS",
    SET_MANGA_ERROR = "SET_MANGA_ERROR",
    SET_RANDOM_MANGA = "SET_RANDOM_MANGA",
    SET_PAGINATED_MANGAS = "SET_PAGINATED_MANGAS",
    SET_LAST_MANGA_PAGE = "SET_LAST_MANGA_PAGE",
    SET_IS_MANGA = "SET_IS_MANGA",
    SET_MANGA_SEARCH_RESULT = "SET_MANGA_SEARCH_RESULT"
}